export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE = "UPDATE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const OPEN_SIGNIN_MODAL = "OPEN_SIGNIN_MODAL";
export const OPEN_SIGNUP_MODAL = "OPEN_SIGNUP_MODAL";
export const CLOSE_SIGNIN_MODAL = "CLOSE_SIGNIN_MODAL";
export const CLOSE_SIGNUP_MODAL = "CLOSE_SIGNUP_MODAL";
export const CLOSE_ALL_MODAL = "CLOSE_ALL_MODAL";
export const LOADING = "LOADING";
export const LOADED = "LOADED";

export const PAGINATE = "PAGINATE";

export const CHANGE_INFORMATION = "CHANGE_INFORMATION";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
